### ISSUE TITLE
Make package available via MELPA stable 

### ISSUE THREAD

**Issue by bdc34** [flexibeast/ewmctrl#14]
Hi!

[MELPA Stable](http://stable.melpa.org/) is the new younger sibling of MELPA for users who'd rather run only stable versions of packages (MELPA can be a bit rocky since every commit comprises a new release), and it would be super cool if ewmctrl could be installed via Stable.

Fortunately it's also really easy to support—all you have to do is define a tag in the `v...` format and you're done. I'd submit a PR if I could, but since tags are global to a project, that's not something possible via PR.

If you're cool with this idea, this should be all you have to do to make it happen:

```shell
$ git tag v1.0.0 3d0217c4d6cdb5c308b6cb4293574f470d4faacf
$ git push origin v1.0.0
```

(Of course, confirm that [3d0217c](https://github.com/flexibeast/ewmctrl/commit/3d0217c4d6cdb5c308b6cb4293574f470d4faacf) is the appropriate commit for the release, but it is the current master so I suspect it is.)

Thanks for your time and consideration!

**Comment by flexibeast** [comment]
Sorry i've taken so long to get to this.

Thanks for the suggestion! i've now tagged that commit accordingly. :-)
